// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terrms/",
        "contact": {
            "name": "yyj",
            "email": "2105753640@qq.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/get/file/data": {
            "get": {
                "description": "\"获取博文\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "blog"
                ],
                "summary": "\"获取博文\"",
                "responses": {
                    "200": {
                        "description": "successfully",
                        "schema": {
                            "$ref": "#/definitions/pkg.Resp"
                        }
                    },
                    "500": {
                        "description": "error happened in server",
                        "schema": {
                            "$ref": "#/definitions/pkg.Resp"
                        }
                    }
                }
            }
        },
        "/get/file/name": {
            "get": {
                "description": "\"获取博文名称\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "blog"
                ],
                "summary": "\"获取博文名称\"",
                "responses": {
                    "200": {
                        "description": "successfully",
                        "schema": {
                            "$ref": "#/definitions/pkg.Resp"
                        }
                    },
                    "500": {
                        "description": "error happened in server",
                        "schema": {
                            "$ref": "#/definitions/pkg.Resp"
                        }
                    }
                }
            }
        },
        "/post/person/login": {
            "post": {
                "description": "\"登录\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "\"登录\"",
                "parameters": [
                    {
                        "description": "账号密码",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "successfully",
                        "schema": {
                            "$ref": "#/definitions/pkg.Resp"
                        }
                    },
                    "500": {
                        "description": "error happened in server",
                        "schema": {
                            "$ref": "#/definitions/pkg.Resp"
                        }
                    }
                }
            }
        },
        "/post/person/register": {
            "post": {
                "description": "\"登录\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "\"登录\"",
                "parameters": [
                    {
                        "description": "账号密码",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "successfully",
                        "schema": {
                            "$ref": "#/definitions/pkg.Resp"
                        }
                    },
                    "500": {
                        "description": "error happened in server",
                        "schema": {
                            "$ref": "#/definitions/pkg.Resp"
                        }
                    }
                }
            }
        },
        "/star/addition": {
            "get": {
                "description": "\"收藏\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "star"
                ],
                "summary": "\"收藏\"",
                "parameters": [
                    {
                        "type": "string",
                        "description": "star",
                        "name": "star",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "successfully",
                        "schema": {
                            "$ref": "#/definitions/pkg.Resp"
                        }
                    },
                    "500": {
                        "description": "error happened in server",
                        "schema": {
                            "$ref": "#/definitions/pkg.Resp"
                        }
                    }
                }
            }
        },
        "/star/delete": {
            "get": {
                "description": "\"收藏\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "star"
                ],
                "summary": "\"收藏\"",
                "parameters": [
                    {
                        "type": "string",
                        "description": "star",
                        "name": "star",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "successfully",
                        "schema": {
                            "$ref": "#/definitions/pkg.Resp"
                        }
                    },
                    "500": {
                        "description": "error happened in server",
                        "schema": {
                            "$ref": "#/definitions/pkg.Resp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.User": {
            "type": "object",
            "required": [
                "account",
                "password"
            ],
            "properties": {
                "account": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "login_time": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "pkg.Resp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0.0",
	Host:        "124.221.246.5:5500",
	BasePath:    "/api",
	Schemes:     []string{"http"},
	Title:       "miniproject",
	Description: "\"赚圈圈API\"",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
